name: Java CI with Maven for Bai 4

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Chỉ định thư mục làm việc mặc định cho job này là Bai9.4
    defaults:
      run:
        working-directory: ./Bai9.4

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Bạn có thể đổi sang 17 hoặc 8 tùy theo phiên bản Java bạn đang dùng
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml